/**
 * Pre-build script: reads registry.json + all source files from packages/registry
 * and generates a TypeScript module with all content inlined.
 *
 * Run before tsup: `tsx scripts/build-registry-data.ts`
 * Output: src/generated/registry-data.ts
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const REGISTRY_ROOT = join(__dirname, '..', '..', 'registry')
const OUTPUT_DIR = join(__dirname, '..', 'src', 'generated')
const OUTPUT_FILE = join(OUTPUT_DIR, 'registry-data.ts')

interface RegistryFile {
  path: string
  target: string
}

interface RegistryItem {
  name: string
  type: string
  description: string
  dependencies: string[]
  registryDependencies: string[]
  files: RegistryFile[]
}

interface Registry {
  name: string
  homepage: string
  items: RegistryItem[]
}

interface RegistryItemWithContent extends RegistryItem {
  files: Array<RegistryFile & { content: string }>
}

function main() {
  const registryPath = join(REGISTRY_ROOT, 'registry.json')
  if (!existsSync(registryPath)) {
    console.error(`Registry not found at ${registryPath}`)
    process.exit(1)
  }

  const registry: Registry = JSON.parse(readFileSync(registryPath, 'utf-8'))

  // Inline all source file contents
  const items: RegistryItemWithContent[] = registry.items.map((item) => {
    const files = item.files.map((file) => {
      const sourcePath = join(REGISTRY_ROOT, file.path)
      let content = ''
      if (existsSync(sourcePath)) {
        content = readFileSync(sourcePath, 'utf-8')
      } else {
        console.warn(`Warning: Source file not found: ${sourcePath}`)
        content = '// Source file not found'
      }
      return { ...file, content }
    })

    return { ...item, files }
  })

  // Generate TypeScript module
  const output = `// AUTO-GENERATED — do not edit manually
// Generated by scripts/build-registry-data.ts

export interface RegistryFile {
  path: string
  target: string
  content: string
}

export interface RegistryItem {
  name: string
  type: string
  description: string
  dependencies: string[]
  registryDependencies: string[]
  files: RegistryFile[]
}

export const registryItems: RegistryItem[] = ${JSON.stringify(items, null, 2)}
`

  mkdirSync(OUTPUT_DIR, { recursive: true })
  writeFileSync(OUTPUT_FILE, output)
  console.log(`Generated registry data: ${items.length} items → ${OUTPUT_FILE}`)
}

main()
